### ISSUE TITLE
Gridcoin Color Palette

### ISSUE THREAD

**Issue by mattcoxonline** [gridcoin-community/Gridcoin-Marketing#10]
I'm going to hopefully start polishing up the Gridcoin Wallet UI soon - making it look a lot more... friendly... but also introduce some of the branding and colour elements.

There's not any "official" Gridcoin colour palette right now, so here's my proposal for the time being. It's mostly puple / indigo / violet, with a scale of greys and then some complimentary colours.

![colors](https://user-images.githubusercontent.com/673542/34883823-176396ac-f7bb-11e7-8d61-e23e7eceee58.png)

Any feedback or suggestions welcome.

### Next steps proposal

- Take on board any feedback and consider it when iterating on the palette
- Update the marketing kit to include relevant swatches and examples of use

### Example of use:

![default 2x](https://user-images.githubusercontent.com/673542/34883861-314bf672-f7bb-11e7-801a-a6be88708708.png)

**Comment by tcblack** [comment]
Nice clean look.
Any chance we could also see "Estimated research owed" as seen on https://gridcoinstats.eu/?

**Comment by wisecracka** [comment]
This looks absolutely fantastic. Might what to play with some oranges in the pallet as well.

**Comment by jring-o** [comment]
love this

**Comment by mattcoxonline** [comment]
> Any chance we could also see "Estimated research owed" as seen on https://gridcoinstats.eu/?

Thanks for the feedback, @tcblack. Right now I'm not working up a real mock for the wallet - this was just an example - but I'll take that into consideration when I get around to it.

> Might what to play with some oranges in the pallet as well.

Yes, @wisecracka. I was considering that and had one or two orange options lined up. I've dropped one in, which you can see here:

<img src="https://raw.githubusercontent.com/mattcoxonline/Gridcoin-Marketing/master/Gridcoin%20Colour%20Palette/Gridcoin%20Colours.png"/>

If there's no more feedback right now, I might just go ahead and create a pull request / merge my changes.

**Comment by Mercosity** [comment]
Definitely need the new Gridcoin logo on the GUI face along with BOINC leaving room fro other logos that may be added later ..

**Comment by denravonska** [comment]
I don't think we need any logos in the main UI as they don't do a whole lot other than wasting screen estate. At _most_ we could add the Gridcoin logo as it can be shrunken down and still be usable, but nobody really does logos in the UI:

Bitcoin
![Bitcoin wallet](https://99bitcoins.com/wp-content/uploads/2017/07/bitcoin-core.jpg)

Ethereum
![Ethereum wallet](https://www.ethereum.org/images/tutorial/Screen-Shot-2015-12-03-at-9.44.42-AM.png)

Word
![Word screenshot](https://blogs.office.com/wp-content/uploads/2015/01/Word_UI_1992x1172.png)

Photoshop (logo for menu button (?))
![Photoshop screenshot](https://bluecorpsumich.files.wordpress.com/2015/11/screenshot-47.png)

Logos in the about window should be enough. Let's keep the UI clean.
